# 
#   docker pull aipiggybot/python
#   docker run --rm -it aipiggybot/python /bin/bash
# 
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


pool:
  vmImage: 'ubuntu-16.04' # examples of other options: 'macOS-10.13', 'vs2017-win2016'


variables:
  dockerId: aipiggybot  
  imageName: python  # Replace with the name of the image you want to publish


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'


- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install -r requirements.txt
  displayName: 'Install tools'

- script: |
    pycodestyle  --show-source --show-pep8 myproj/util/*.py tests/*.py 
  displayName: 'PEP8 Code Style Check'

- script: |
    pip install pytest
    pip install pytest-cov
    pytest --cov-report=xml --cov=myproj -p no:warnings tests/
  displayName: 'Test with pytest'

- script: |
    pip install codecov
    codecov --token="${CODECOV_TOKEN}"
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)
  displayName: 'CodeCov'

- script: |
    make
    make test
  displayName: 'Docker make'

# Docker
- script: |
    set -e
    docker build --no-cache -t $(dockerId)/$(imageName) .
    echo "${DOCKERPASSWORD}"| docker login -u=$(dockerId) --password-stdin
    docker push $(dockerId)/$(imageName)
    docker logout
  env:
    DOCKERPASSWORD: $(dockerPassword)
  displayName: 'Make docker image public'
